"""empty message

Revision ID: c01f5b436193
Revises: 70514466782b
Create Date: 2023-01-10 20:19:12.568122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01f5b436193'
down_revision = '70514466782b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_warehouse_to_id_fkey', 'document', type_='foreignkey')
    op.drop_column('document', 'warehouse_to_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('warehouse_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('document_warehouse_to_id_fkey', 'document', 'warehouse', ['warehouse_to_id'], ['id'])
    # ### end Alembic commands ###
