"""empty message

Revision ID: ce49915cc925
Revises: 227b5817c79d
Create Date: 2023-01-10 18:13:29.153530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce49915cc925'
down_revision = '227b5817c79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue', sa.Column('edition_id', sa.Integer(), nullable=False))
    op.add_column('catalogue', sa.Column('language_id', sa.Integer(), nullable=False))
    op.add_column('catalogue', sa.Column('platform_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'catalogue', 'platform', ['platform_id'], ['id'])
    op.create_foreign_key(None, 'catalogue', 'edition', ['edition_id'], ['id'])
    op.create_foreign_key(None, 'catalogue', 'language', ['language_id'], ['id'])
    op.drop_column('catalogue', 'burning_time')
    op.drop_column('catalogue', 'width')
    op.drop_column('catalogue', 'diameter')
    op.drop_column('catalogue', 'height')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue', sa.Column('height', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('catalogue', sa.Column('diameter', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('catalogue', sa.Column('width', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('catalogue', sa.Column('burning_time', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'catalogue', type_='foreignkey')
    op.drop_constraint(None, 'catalogue', type_='foreignkey')
    op.drop_constraint(None, 'catalogue', type_='foreignkey')
    op.drop_column('catalogue', 'platform_id')
    op.drop_column('catalogue', 'language_id')
    op.drop_column('catalogue', 'edition_id')
    # ### end Alembic commands ###
